<?php
/**
 * TransactionalMessagingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud\PHPSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SalesForce\MarketingCloud\PHPSDK;

use \SalesForce\MarketingCloud\PHPSDK\Configuration;
use \SalesForce\MarketingCloud\PHPSDK\ApiException;
use \SalesForce\MarketingCloud\PHPSDK\ObjectSerializer;

/**
 * TransactionalMessagingApiTest Class Doc Comment
 *
 * @category Class
 * @package  SalesForce\MarketingCloud\PHPSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionalMessagingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEmailDefinition
     *
     * createEmailDefinition.
     *
     */
    public function testCreateEmailDefinition()
    {
    }

    /**
     * Test case for createSmsDefinition
     *
     * createSmsDefinition.
     *
     */
    public function testCreateSmsDefinition()
    {
    }

    /**
     * Test case for deleteEmailDefinition
     *
     * deleteEmailDefinition.
     *
     */
    public function testDeleteEmailDefinition()
    {
    }

    /**
     * Test case for deleteQueuedMessagesForEmailDefinition
     *
     * deleteQueuedMessagesForEmailDefinition.
     *
     */
    public function testDeleteQueuedMessagesForEmailDefinition()
    {
    }

    /**
     * Test case for deleteQueuedMessagesForSmsDefinition
     *
     * deleteQueuedMessagesForSmsDefinition.
     *
     */
    public function testDeleteQueuedMessagesForSmsDefinition()
    {
    }

    /**
     * Test case for deleteSmsDefinition
     *
     * deleteSmsDefinition.
     *
     */
    public function testDeleteSmsDefinition()
    {
    }

    /**
     * Test case for getEmailDefinition
     *
     * getEmailDefinition.
     *
     */
    public function testGetEmailDefinition()
    {
    }

    /**
     * Test case for getEmailDefinitions
     *
     * getEmailDefinitions.
     *
     */
    public function testGetEmailDefinitions()
    {
    }

    /**
     * Test case for getEmailSendStatusForRecipient
     *
     * getEmailSendStatusForRecipient.
     *
     */
    public function testGetEmailSendStatusForRecipient()
    {
    }

    /**
     * Test case for getEmailsNotSentToRecipients
     *
     * getEmailsNotSentToRecipients.
     *
     */
    public function testGetEmailsNotSentToRecipients()
    {
    }

    /**
     * Test case for getQueueMetricsForEmailDefinition
     *
     * getQueueMetricsForEmailDefinition.
     *
     */
    public function testGetQueueMetricsForEmailDefinition()
    {
    }

    /**
     * Test case for getQueueMetricsForSmsDefinition
     *
     * getQueueMetricsForSmsDefinition.
     *
     */
    public function testGetQueueMetricsForSmsDefinition()
    {
    }

    /**
     * Test case for getSMSsNotSentToRecipients
     *
     * getSMSsNotSentToRecipients.
     *
     */
    public function testGetSMSsNotSentToRecipients()
    {
    }

    /**
     * Test case for getSmsDefinition
     *
     * getSmsDefinition.
     *
     */
    public function testGetSmsDefinition()
    {
    }

    /**
     * Test case for getSmsDefinitions
     *
     * getSmsDefinitions.
     *
     */
    public function testGetSmsDefinitions()
    {
    }

    /**
     * Test case for getSmsSendStatusForRecipient
     *
     * getSmsSendStatusForRecipient.
     *
     */
    public function testGetSmsSendStatusForRecipient()
    {
    }

    /**
     * Test case for partiallyUpdateEmailDefinition
     *
     * partiallyUpdateEmailDefinition.
     *
     */
    public function testPartiallyUpdateEmailDefinition()
    {
    }

    /**
     * Test case for partiallyUpdateSmsDefinition
     *
     * partiallyUpdateSmsDefinition.
     *
     */
    public function testPartiallyUpdateSmsDefinition()
    {
    }

    /**
     * Test case for sendEmailToMultipleRecipients
     *
     * sendEmailToMultipleRecipients.
     *
     */
    public function testSendEmailToMultipleRecipients()
    {
    }

    /**
     * Test case for sendEmailToSingleRecipient
     *
     * sendEmailToSingleRecipient.
     *
     */
    public function testSendEmailToSingleRecipient()
    {
    }

    /**
     * Test case for sendSmsToMultipleRecipients
     *
     * sendSmsToMultipleRecipients.
     *
     */
    public function testSendSmsToMultipleRecipients()
    {
    }

    /**
     * Test case for sendSmsToSingleRecipient
     *
     * sendSmsToSingleRecipient.
     *
     */
    public function testSendSmsToSingleRecipient()
    {
    }
}
