<?php
/**
 * Asset
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud\PHPSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SalesForce\MarketingCloud\PHPSDK\Model;

use \ArrayAccess;
use \SalesForce\MarketingCloud\PHPSDK\ObjectSerializer;

/**
 * Asset Class Doc Comment
 *
 * @category Class
 * @package  SalesForce\MarketingCloud\PHPSDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Asset implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Asset';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'float',
        'customer_key' => 'string',
        'content_type' => 'string',
        'data' => 'object',
        'asset_type' => '\SalesForce\MarketingCloud\PHPSDK\Model\AssetType',
        'version' => 'float',
        'locked' => 'bool',
        'file_properties' => 'object',
        'name' => 'string',
        'description' => 'string',
        'category' => 'object',
        'tags' => 'string[]',
        'content' => 'string',
        'design' => 'string',
        'super_content' => 'string',
        'custom_fields' => 'object',
        'views' => 'object',
        'blocks' => 'object',
        'min_blocks' => 'float',
        'max_blocks' => 'float',
        'channels' => 'object',
        'allowed_blocks' => 'string[]',
        'slots' => 'object',
        'business_unit_availability' => 'object',
        'sharing_properties' => '\SalesForce\MarketingCloud\PHPSDK\Model\SharingProperties',
        'template' => 'object',
        'file' => 'string',
        'generate_from' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'customer_key' => null,
        'content_type' => null,
        'data' => null,
        'asset_type' => null,
        'version' => null,
        'locked' => null,
        'file_properties' => null,
        'name' => null,
        'description' => null,
        'category' => null,
        'tags' => null,
        'content' => null,
        'design' => null,
        'super_content' => null,
        'custom_fields' => null,
        'views' => null,
        'blocks' => null,
        'min_blocks' => null,
        'max_blocks' => null,
        'channels' => null,
        'allowed_blocks' => null,
        'slots' => null,
        'business_unit_availability' => null,
        'sharing_properties' => null,
        'template' => null,
        'file' => null,
        'generate_from' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'customer_key' => 'customerKey',
        'content_type' => 'contentType',
        'data' => 'data',
        'asset_type' => 'assetType',
        'version' => 'version',
        'locked' => 'locked',
        'file_properties' => 'fileProperties',
        'name' => 'name',
        'description' => 'description',
        'category' => 'category',
        'tags' => 'tags',
        'content' => 'content',
        'design' => 'design',
        'super_content' => 'superContent',
        'custom_fields' => 'customFields',
        'views' => 'views',
        'blocks' => 'blocks',
        'min_blocks' => 'minBlocks',
        'max_blocks' => 'maxBlocks',
        'channels' => 'channels',
        'allowed_blocks' => 'allowedBlocks',
        'slots' => 'slots',
        'business_unit_availability' => 'businessUnitAvailability',
        'sharing_properties' => 'sharingProperties',
        'template' => 'template',
        'file' => 'file',
        'generate_from' => 'generateFrom'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'customer_key' => 'setCustomerKey',
        'content_type' => 'setContentType',
        'data' => 'setData',
        'asset_type' => 'setAssetType',
        'version' => 'setVersion',
        'locked' => 'setLocked',
        'file_properties' => 'setFileProperties',
        'name' => 'setName',
        'description' => 'setDescription',
        'category' => 'setCategory',
        'tags' => 'setTags',
        'content' => 'setContent',
        'design' => 'setDesign',
        'super_content' => 'setSuperContent',
        'custom_fields' => 'setCustomFields',
        'views' => 'setViews',
        'blocks' => 'setBlocks',
        'min_blocks' => 'setMinBlocks',
        'max_blocks' => 'setMaxBlocks',
        'channels' => 'setChannels',
        'allowed_blocks' => 'setAllowedBlocks',
        'slots' => 'setSlots',
        'business_unit_availability' => 'setBusinessUnitAvailability',
        'sharing_properties' => 'setSharingProperties',
        'template' => 'setTemplate',
        'file' => 'setFile',
        'generate_from' => 'setGenerateFrom'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'customer_key' => 'getCustomerKey',
        'content_type' => 'getContentType',
        'data' => 'getData',
        'asset_type' => 'getAssetType',
        'version' => 'getVersion',
        'locked' => 'getLocked',
        'file_properties' => 'getFileProperties',
        'name' => 'getName',
        'description' => 'getDescription',
        'category' => 'getCategory',
        'tags' => 'getTags',
        'content' => 'getContent',
        'design' => 'getDesign',
        'super_content' => 'getSuperContent',
        'custom_fields' => 'getCustomFields',
        'views' => 'getViews',
        'blocks' => 'getBlocks',
        'min_blocks' => 'getMinBlocks',
        'max_blocks' => 'getMaxBlocks',
        'channels' => 'getChannels',
        'allowed_blocks' => 'getAllowedBlocks',
        'slots' => 'getSlots',
        'business_unit_availability' => 'getBusinessUnitAvailability',
        'sharing_properties' => 'getSharingProperties',
        'template' => 'getTemplate',
        'file' => 'getFile',
        'generate_from' => 'getGenerateFrom'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['customer_key'] = isset($data['customer_key']) ? $data['customer_key'] : null;
        $this->container['content_type'] = isset($data['content_type']) ? $data['content_type'] : null;
        $this->container['data'] = isset($data['data']) ? $data['data'] : null;
        $this->container['asset_type'] = isset($data['asset_type']) ? $data['asset_type'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['locked'] = isset($data['locked']) ? $data['locked'] : null;
        $this->container['file_properties'] = isset($data['file_properties']) ? $data['file_properties'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['content'] = isset($data['content']) ? $data['content'] : null;
        $this->container['design'] = isset($data['design']) ? $data['design'] : null;
        $this->container['super_content'] = isset($data['super_content']) ? $data['super_content'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
        $this->container['views'] = isset($data['views']) ? $data['views'] : null;
        $this->container['blocks'] = isset($data['blocks']) ? $data['blocks'] : null;
        $this->container['min_blocks'] = isset($data['min_blocks']) ? $data['min_blocks'] : null;
        $this->container['max_blocks'] = isset($data['max_blocks']) ? $data['max_blocks'] : null;
        $this->container['channels'] = isset($data['channels']) ? $data['channels'] : null;
        $this->container['allowed_blocks'] = isset($data['allowed_blocks']) ? $data['allowed_blocks'] : null;
        $this->container['slots'] = isset($data['slots']) ? $data['slots'] : null;
        $this->container['business_unit_availability'] = isset($data['business_unit_availability']) ? $data['business_unit_availability'] : null;
        $this->container['sharing_properties'] = isset($data['sharing_properties']) ? $data['sharing_properties'] : null;
        $this->container['template'] = isset($data['template']) ? $data['template'] : null;
        $this->container['file'] = isset($data['file']) ? $data['file'] : null;
        $this->container['generate_from'] = isset($data['generate_from']) ? $data['generate_from'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['customer_key'] === null) {
            $invalidProperties[] = "'customer_key' can't be null";
        }
        if ($this->container['asset_type'] === null) {
            $invalidProperties[] = "'asset_type' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return float
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param float $id The id of the asset
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets customer_key
     *
     * @return string
     */
    public function getCustomerKey()
    {
        return $this->container['customer_key'];
    }

    /**
     * Sets customer_key
     *
     * @param string $customer_key Reference to customer's private ID/name for the asset
     *
     * @return $this
     */
    public function setCustomerKey($customer_key)
    {
        $this->container['customer_key'] = $customer_key;

        return $this;
    }

    /**
     * Gets content_type
     *
     * @return string
     */
    public function getContentType()
    {
        return $this->container['content_type'];
    }

    /**
     * Sets content_type
     *
     * @param string $content_type The type that the content attribute will be in
     *
     * @return $this
     */
    public function setContentType($content_type)
    {
        $this->container['content_type'] = $content_type;

        return $this;
    }

    /**
     * Gets data
     *
     * @return object
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param object $data Property bag containing the asset data
     *
     * @return $this
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets asset_type
     *
     * @return \SalesForce\MarketingCloud\PHPSDK\Model\AssetType
     */
    public function getAssetType()
    {
        return $this->container['asset_type'];
    }

    /**
     * Sets asset_type
     *
     * @param \SalesForce\MarketingCloud\PHPSDK\Model\AssetType $asset_type asset_type
     *
     * @return $this
     */
    public function setAssetType($asset_type)
    {
        $this->container['asset_type'] = $asset_type;

        return $this;
    }

    /**
     * Gets version
     *
     * @return float
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param float $version The version of the asset
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets locked
     *
     * @return bool
     */
    public function getLocked()
    {
        return $this->container['locked'];
    }

    /**
     * Sets locked
     *
     * @param bool $locked Specifies if the asset can be modified or not
     *
     * @return $this
     */
    public function setLocked($locked)
    {
        $this->container['locked'] = $locked;

        return $this;
    }

    /**
     * Gets file_properties
     *
     * @return object
     */
    public function getFileProperties()
    {
        return $this->container['file_properties'];
    }

    /**
     * Sets file_properties
     *
     * @param object $file_properties Stores the different properties that this asset refers to if it is a file type
     *
     * @return $this
     */
    public function setFileProperties($file_properties)
    {
        $this->container['file_properties'] = $file_properties;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the asset, set by the client
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Description of the asset, set by the client
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets category
     *
     * @return object
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param object $category ID of the category the asset belongs to
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[] $tags List of tags associated with the asset
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string $content The actual content of the asset
     *
     * @return $this
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets design
     *
     * @return string
     */
    public function getDesign()
    {
        return $this->container['design'];
    }

    /**
     * Sets design
     *
     * @param string $design Fallback for display when neither content nor supercontent are provided
     *
     * @return $this
     */
    public function setDesign($design)
    {
        $this->container['design'] = $design;

        return $this;
    }

    /**
     * Gets super_content
     *
     * @return string
     */
    public function getSuperContent()
    {
        return $this->container['super_content'];
    }

    /**
     * Sets super_content
     *
     * @param string $super_content Content that supersedes content in terms of display
     *
     * @return $this
     */
    public function setSuperContent($super_content)
    {
        $this->container['super_content'] = $super_content;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object $custom_fields Custom fields within an asset
     *
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets views
     *
     * @return object
     */
    public function getViews()
    {
        return $this->container['views'];
    }

    /**
     * Sets views
     *
     * @param object $views Views within an asset
     *
     * @return $this
     */
    public function setViews($views)
    {
        $this->container['views'] = $views;

        return $this;
    }

    /**
     * Gets blocks
     *
     * @return object
     */
    public function getBlocks()
    {
        return $this->container['blocks'];
    }

    /**
     * Sets blocks
     *
     * @param object $blocks Blocks within the asset
     *
     * @return $this
     */
    public function setBlocks($blocks)
    {
        $this->container['blocks'] = $blocks;

        return $this;
    }

    /**
     * Gets min_blocks
     *
     * @return float
     */
    public function getMinBlocks()
    {
        return $this->container['min_blocks'];
    }

    /**
     * Sets min_blocks
     *
     * @param float $min_blocks Minimum number of blocks within an asset
     *
     * @return $this
     */
    public function setMinBlocks($min_blocks)
    {
        $this->container['min_blocks'] = $min_blocks;

        return $this;
    }

    /**
     * Gets max_blocks
     *
     * @return float
     */
    public function getMaxBlocks()
    {
        return $this->container['max_blocks'];
    }

    /**
     * Sets max_blocks
     *
     * @param float $max_blocks Maximum number of blocks within an asset
     *
     * @return $this
     */
    public function setMaxBlocks($max_blocks)
    {
        $this->container['max_blocks'] = $max_blocks;

        return $this;
    }

    /**
     * Gets channels
     *
     * @return object
     */
    public function getChannels()
    {
        return $this->container['channels'];
    }

    /**
     * Sets channels
     *
     * @param object $channels List of channels that are allowed to use this asset
     *
     * @return $this
     */
    public function setChannels($channels)
    {
        $this->container['channels'] = $channels;

        return $this;
    }

    /**
     * Gets allowed_blocks
     *
     * @return string[]
     */
    public function getAllowedBlocks()
    {
        return $this->container['allowed_blocks'];
    }

    /**
     * Sets allowed_blocks
     *
     * @param string[] $allowed_blocks List of blocks that are allowed in the asset
     *
     * @return $this
     */
    public function setAllowedBlocks($allowed_blocks)
    {
        $this->container['allowed_blocks'] = $allowed_blocks;

        return $this;
    }

    /**
     * Gets slots
     *
     * @return object
     */
    public function getSlots()
    {
        return $this->container['slots'];
    }

    /**
     * Sets slots
     *
     * @param object $slots Slots within the asset
     *
     * @return $this
     */
    public function setSlots($slots)
    {
        $this->container['slots'] = $slots;

        return $this;
    }

    /**
     * Gets business_unit_availability
     *
     * @return object
     */
    public function getBusinessUnitAvailability()
    {
        return $this->container['business_unit_availability'];
    }

    /**
     * Sets business_unit_availability
     *
     * @param object $business_unit_availability A dictionary of member IDs that have been granted access to the asset
     *
     * @return $this
     */
    public function setBusinessUnitAvailability($business_unit_availability)
    {
        $this->container['business_unit_availability'] = $business_unit_availability;

        return $this;
    }

    /**
     * Gets sharing_properties
     *
     * @return \SalesForce\MarketingCloud\PHPSDK\Model\SharingProperties
     */
    public function getSharingProperties()
    {
        return $this->container['sharing_properties'];
    }

    /**
     * Sets sharing_properties
     *
     * @param \SalesForce\MarketingCloud\PHPSDK\Model\SharingProperties $sharing_properties sharing_properties
     *
     * @return $this
     */
    public function setSharingProperties($sharing_properties)
    {
        $this->container['sharing_properties'] = $sharing_properties;

        return $this;
    }

    /**
     * Gets template
     *
     * @return object
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param object $template Template the asset follows
     *
     * @return $this
     */
    public function setTemplate($template)
    {
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets file
     *
     * @return string
     */
    public function getFile()
    {
        return $this->container['file'];
    }

    /**
     * Sets file
     *
     * @param string $file Base64-encoded string of a file associated with an asset
     *
     * @return $this
     */
    public function setFile($file)
    {
        $this->container['file'] = $file;

        return $this;
    }

    /**
     * Gets generate_from
     *
     * @return string
     */
    public function getGenerateFrom()
    {
        return $this->container['generate_from'];
    }

    /**
     * Sets generate_from
     *
     * @param string $generate_from Tells the sending compiler what view to use for generating this view's content
     *
     * @return $this
     */
    public function setGenerateFrom($generate_from)
    {
        $this->container['generate_from'] = $generate_from;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


