<?php
/**
 * CampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SalesForce\MarketingCloud\Test\Api;

use GuzzleHttp\Client;
use SalesForce\MarketingCloud\ApiException;
use SalesForce\MarketingCloud\TestHelper\Authorization\AuthServiceTestFactory;
use SalesForce\MarketingCloud\TestHelper\Api\BaseApiTest;
use SalesForce\MarketingCloud\Configuration;
use SalesForce\MarketingCloud\Api\AbstractApi;
use SalesForce\MarketingCloud\Api\CampaignApi;

/**
 * CampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignApiTest extends BaseApiTest
{
    /**
     * @var string
     */
    protected static $modelNamespace = "\SalesForce\MarketingCloud\Model";

    /**
     * Creates the client required to do the API calls
     *
     * @return CampaignApi|AbstractApi
     */
    protected function createClient(): AbstractApi
    {
        if (null === $this->client) {
            $config = new Configuration();
            $config->setHost(getenv("API_URL"));

            $this->client = new CampaignApi(
                [AuthServiceTestFactory::class, 'factory'],
                new Client(['verify' => false]),
                $config
            );
        }

        return $this->client;
    }

    
    /**
     * Test case for createCampaign
     *
     * createCampaign.
     *
     */
    public function testCreateCampaign()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\Campaign"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("POST", "createCampaign");
    }
    
    /**
     * Test case for deleteCampaignById
     *
     * deleteCampaignById.
     *
     */
    public function testDeleteCampaignById()
    {
        $this->expectException(ApiException::class);
        $this->getExpectedExceptionCode(400);

        $this->setHttpMethod("DELETE");
        $this->setModelClass(
            __FUNCTION__,
            ""
        );

        $this->createResourceOnEndpoint();

        // The actual test
        $resourceId = $this->getResourceId();
        $client = $this->createClient();

        $client->deleteCampaignById($resourceId);
        $client->getCampaignById($resourceId);
    }
    
    /**
     * Test case for getCampaignById
     *
     * getCampaignById.
     *
     */
    public function testGetCampaignById()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\Campaign"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getCampaignById");
    }
}
