<?php
/**
 * CampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SalesForce\MarketingCloud\Test\Api;

use SalesForce\MarketingCloud\ApiException;
use SalesForce\MarketingCloud\TestHelper\Api\BaseApiTest;

/**
 * CampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignApiTest extends BaseApiTest
{
    /**
     * The client class to use in order to build the client object
     *
     * @var string
     */
    protected $clientClass = \SalesForce\MarketingCloud\Api\CampaignApi::class;

    /**
     * @var string
     */
    protected static $modelNamespace = "\SalesForce\MarketingCloud\Model";

    
    /**
     * Test case for createCampaign
     *
     * createCampaign.
     * @throws \Exception
     */
    public function testCreateCampaign()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\Campaign"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("POST", "createCampaign");
    }

    /**
     * Test case for deleteCampaignById
     *
     * deleteCampaignById.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testDeleteCampaignById()
    {
        $this->expectException(ApiException::class);
        $this->expectExceptionCode(400);

        $this->setHttpMethod("DELETE");
        $this->setModelClass(
            __FUNCTION__,
            ""
        );

        $this->createResourceOnEndpoint();

        // The actual test
        $resourceId = $this->getResourceId();

        /** @var \SalesForce\MarketingCloud\Api\CampaignApi $client */
        $client = $this->getClient();

        $client->deleteCampaignById($resourceId);
        $client->getCampaignById($resourceId);
    }
    
    /**
     * Test case for getCampaignById
     *
     * getCampaignById.
     * @throws \Exception
     */
    public function testGetCampaignById()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\Campaign"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getCampaignById");
    }
}
