<?php
/**
 * TransactionalMessagingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SalesForce\MarketingCloud\Test\Api;

use PHPUnit\Framework\ExpectationFailedException;
use SalesForce\MarketingCloud\Model\Recipient;
use SalesForce\MarketingCloud\Model\SendEmailToMultipleRecipientsRequest;
use SalesForce\MarketingCloud\Model\SendEmailToSingleRecipientRequest;
use SalesForce\MarketingCloud\Model\SendSmsToMultipleRecipientsRequest;
use SalesForce\MarketingCloud\Model\SendSmsToSingleRecipientRequest;
use SalesForce\MarketingCloud\TestHelper\Api\BaseApiTest;
use SalesForce\MarketingCloud\TestHelper\Model\Provider\EmailDefinitionProvider;
use SalesForce\MarketingCloud\TestHelper\Model\Provider\SmsDefinitionProvider;
use SalesForce\MarketingCloud\TestHelper\Model\Provisioner\EmailDefinition;
use SalesForce\MarketingCloud\TestHelper\Model\Provisioner\SmsDefinition;

/**
 * TransactionalMessagingApiTest Class Doc Comment
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionalMessagingApiTest extends BaseApiTest
{
    /**
     * The client class to use in order to build the client object
     *
     * @var string
     */
    protected $clientClass = \SalesForce\MarketingCloud\Api\TransactionalMessagingApi::class;

    /**
     * @var string
     */
    protected static $modelNamespace = "\SalesForce\MarketingCloud\Model";


    /**
     * Test case for createEmailDefinition
     *
     * createEmailDefinition.
     * @throws \Exception
     */
    public function testCreateEmailDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateEmailDefinitionRequest"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("POST", "createEmailDefinition");
    }

    /**
     * Test case for createSmsDefinition
     *
     * createSmsDefinition.
     * @throws \Exception
     */
    public function testCreateSmsDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateSmsDefinitionRequest"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("POST", "createSmsDefinition");
    }

    /**
     * Test case for deleteEmailDefinition
     *
     * deleteEmailDefinition.
     * @throws \Exception
     */
    public function testDeleteEmailDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\DeleteSendDefinitionResponse"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("DELETE", "deleteEmailDefinition");
    }

    /**
     * Test case for deleteQueuedMessagesForEmailDefinition
     *
     * deleteQueuedMessagesForEmailDefinition.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testDeleteQueuedMessagesForEmailDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\DeleteQueuedMessagesForSendDefinitionResponse"
        );

        $this->createResourceOnEndpoint();

        // The actual test
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();
        $response = $client->deleteQueuedMessagesForEmailDefinition($this->getResourceId());

        $this->assertNotNull($response->getRequestId());
    }

    /**
     * Test case for deleteQueuedMessagesForSmsDefinition
     *
     * deleteQueuedMessagesForSmsDefinition.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testDeleteQueuedMessagesForSmsDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\DeleteQueuedMessagesForSendDefinitionResponse"
        );

        $this->createResourceOnEndpoint();

        // The actual test
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();
        $response = $client->deleteQueuedMessagesForSmsDefinition($this->getResourceId());

        $this->assertNotNull($response->getRequestId());
    }

    /**
     * Test case for deleteSmsDefinition
     *
     * deleteSmsDefinition.
     * @throws \Exception
     */
    public function testDeleteSmsDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\DeleteSendDefinitionResponse"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("DELETE", "deleteSmsDefinition");
    }

    /**
     * Test case for getEmailDefinition
     *
     * getEmailDefinition.
     * @throws \Exception
     */
    public function testGetEmailDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateEmailDefinitionRequest"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getEmailDefinition");
    }

    /**
     * Test case for getEmailDefinitions
     *
     * getEmailDefinitions.
     * @throws \Exception
     */
    public function testGetEmailDefinitions()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\GetEmailDefinitionsResponse"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getEmailDefinitions");
    }

    /**
     * Test case for getEmailSendStatusForRecipient
     *
     * getEmailSendStatusForRecipient.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetEmailSendStatusForRecipient()
    {
        $eventCategories = [
            "TransactionalSendEvents.EmailSent",
            "TransactionalSendEvents.EmailQueued",
            "TransactionalSendEvents.EmailNotSent"
        ];

        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();

        // Create the email definition
        $provisioner = new EmailDefinition();
        $provisioner->setContainer(static::$container);

        $definition = $provisioner->provision(EmailDefinitionProvider::getTestModel());
        $definition = $client->createEmailDefinition($definition);

        // Construct the email request
        $messageKey = md5(rand(0, 9999));
        $recipient = new Recipient([
            "contactKey" => "johnDoe@gmail.com"
        ]);

        $messageRequestBody = new SendEmailToSingleRecipientRequest([
            "definitionKey" => $definition->getDefinitionKey(),
            "recipient" => $recipient
        ]);

        // SUT
        $client->sendEmailToSingleRecipient($messageKey, $messageRequestBody);

        // Effect check
        $result = $client->getEmailSendStatusForRecipient($messageKey);

        try {
            $this->assertNotNull($result->getRequestId());
            $this->assertContains($result->getEventCategoryType(), $eventCategories);
        } catch (ExpectationFailedException $e) {
            throw $e;
        } finally {
            $client->deleteEmailDefinition($definition->getDefinitionKey());
            $provisioner->deplete($definition);
        }
    }

    /**
     * Test case for getEmailsNotSentToRecipients
     *
     * getEmailsNotSentToRecipients.
     *
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @throws \SalesForce\MarketingCloud\ApiException
     * @throws \Exception
     */
    public function testGetEmailsNotSentToRecipients()
    {
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();
        $response = $client->getEmailsNotSentToRecipients("notSent");

        $this->assertNotNull($response->getRequestId());
        $this->assertNotNull($response->getCount());
    }

    /**
     * Test case for getQueueMetricsForEmailDefinition
     *
     * getQueueMetricsForEmailDefinition.
     * @throws \Exception
     */
    public function testGetQueueMetricsForEmailDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\GetQueueMetricsForSendDefinitionResponse"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getQueueMetricsForEmailDefinition");
    }

    /**
     * Test case for getQueueMetricsForSmsDefinition
     *
     * getQueueMetricsForSmsDefinition.
     * @throws \Exception
     */
    public function testGetQueueMetricsForSmsDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\GetQueueMetricsForSendDefinitionResponse"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getQueueMetricsForSmsDefinition");
    }

    /**
     * Test case for getSMSsNotSentToRecipients
     *
     * getSMSsNotSentToRecipients.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetSMSsNotSentToRecipients()
    {
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();
        $response = $client->getSMSsNotSentToRecipients("notSent");

        $this->assertNotNull($response->getRequestId());
        $this->assertNotNull($response->getCount());
    }

    /**
     * Test case for getSmsDefinition
     *
     * getSmsDefinition.
     * @throws \Exception
     */
    public function testGetSmsDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateSmsDefinitionRequest"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getSmsDefinition");
    }

    /**
     * Test case for getSmsDefinitions
     *
     * getSmsDefinitions.
     * @throws \Exception
     */
    public function testGetSmsDefinitions()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\GetSmsDefinitionsResponse"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("GET", "getSmsDefinitions");
    }

    /**
     * Test case for getSmsSendStatusForRecipient
     *
     * getSmsSendStatusForRecipient.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetSmsSendStatusForRecipient()
    {
        $eventCategories = [
            "TransactionalSendEvents.SMSSent",
            "TransactionalSendEvents.SMSQueued",
            "TransactionalSendEvents.SMSNotSent"
        ];

        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();

        // Create the email definition
        $provisioner = new SmsDefinition();
        $provisioner->setContainer(static::$container);

        $definition = $provisioner->provision(SmsDefinitionProvider::getTestModel());
        $definition = $client->createSmsDefinition($definition);

        // Construct the email request
        $messageKey = md5(rand(0, 9999));
        $recipient = new Recipient([
            "contactKey" => "johnDoe@gmail.com"
        ]);

        $body = new SendSmsToSingleRecipientRequest([
            "definitionKey" => $definition->getDefinitionKey(),
            "recipient" => $recipient
        ]);

        // SUT
        $client->sendSmsToSingleRecipient($messageKey, $body);

        // Effect check
        $result = $client->getSmsSendStatusForRecipient($messageKey);

        try {
            $this->assertNotNull($result->getRequestId());
            $this->assertContains($result->getEventCategoryType(), $eventCategories);
        } catch (ExpectationFailedException $e) {
            throw $e;
        } finally {
            $client->deleteSmsDefinition($definition->getDefinitionKey());
            $provisioner->deplete($definition);
        }
    }

    /**
     * Test case for partiallyUpdateEmailDefinition
     *
     * partiallyUpdateEmailDefinition.
     * @throws \Exception
     */
    public function testPartiallyUpdateEmailDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateEmailDefinitionRequest"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("PATCH", "partiallyUpdateEmailDefinition");
    }

    /**
     * Test case for partiallyUpdateSmsDefinition
     *
     * partiallyUpdateSmsDefinition.
     * @throws \Exception
     */
    public function testPartiallyUpdateSmsDefinition()
    {
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateSmsDefinitionRequest"
        );

        $this->createResourceOnEndpoint();
        $this->executeOperation("PATCH", "partiallyUpdateSmsDefinition");
    }

    /**
     * Test case for sendEmailToMultipleRecipients
     *
     * sendEmailToMultipleRecipients.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testSendEmailToMultipleRecipients()
    {
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();

        // Create the email definition
        $provisioner = new EmailDefinition();
        $provisioner->setContainer(static::$container);

        $definition = $provisioner->provision(EmailDefinitionProvider::getTestModel());
        $definition = $client->createEmailDefinition($definition);

        $messageRequestBody = new SendEmailToMultipleRecipientsRequest([
            "definitionKey" => $definition->getDefinitionKey(),
            "recipients" => [
                new Recipient(["contactKey" => "johnDoe@gmail.com"]),
                new Recipient(["contactKey" => "johnDoe2@gmail.com"]),
            ]
        ]);

        // SUT
        $result = $client->sendEmailToMultipleRecipients($messageRequestBody);

        try {
            $this->assertNotNull($result->getRequestId());
        } catch (ExpectationFailedException $e) {
            throw $e;
        } finally {
            $client->deleteEmailDefinition($definition->getDefinitionKey());
            $provisioner->deplete($definition);
        }
    }

    /**
     * Test case for sendEmailToSingleRecipient
     *
     * sendEmailToSingleRecipient.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testSendEmailToSingleRecipient()
    {
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();

        // Create the email definition
        $provisioner = new EmailDefinition();
        $provisioner->setContainer(static::$container);

        $definition = $provisioner->provision(EmailDefinitionProvider::getTestModel());
        $definition = $client->createEmailDefinition($definition);

        // Construct the email request
        $messageKey = md5(rand(0, 9999));
        $recipient = new Recipient([
            "contactKey" => "johnDoe@gmail.com"
        ]);

        $messageRequestBody = new SendEmailToSingleRecipientRequest([
            "definitionKey" => $definition->getDefinitionKey(),
            "recipient" => $recipient
        ]);

        // SUT
        $result = $client->sendEmailToSingleRecipient($messageKey, $messageRequestBody);

        try {
            $this->assertNotNull($result->getRequestId());
        } catch (ExpectationFailedException $e) {
            throw $e;
        } finally {
            $client->deleteEmailDefinition($definition->getDefinitionKey());
            $provisioner->deplete($definition);
        }
    }

    /**
     * Test case for sendSmsToMultipleRecipients
     *
     * sendSmsToMultipleRecipients.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testSendSmsToMultipleRecipients()
    {
        /** @var \SalesForce\MarketingCloud\Api\TransactionalMessagingApi $client */
        $client = $this->getClient();

        // Create the email definition
        $provisioner = new SmsDefinition();
        $provisioner->setContainer(static::$container);

        $definition = $provisioner->provision(SmsDefinitionProvider::getTestModel());
        $definition = $client->createSmsDefinition($definition);

        $body = new SendSmsToMultipleRecipientsRequest([
            "definitionKey" => $definition->getDefinitionKey(),
            "recipients" => [
                new Recipient(["contactKey" => "johnDoe@gmail.com"]),
                new Recipient(["contactKey" => "johnDoe2@gmail.com"]),
            ]
        ]);

        // SUT
        $result = $client->sendSmsToMultipleRecipients($body);

        try {
            $this->assertNotNull($result->getRequestId());
        } catch (ExpectationFailedException $e) {
            throw $e;
        } finally {
            $client->deleteSmsDefinition($definition->getDefinitionKey());
            $provisioner->deplete($definition);
        }
    }

    /**
     * Test case for sendSmsToSingleRecipient
     *
     * sendSmsToSingleRecipient.
     * @throws \Exception
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testSendSmsToSingleRecipient()
    {
        // Looking for a decorator first
        /** @var \SalesForce\MarketingCloud\TestHelper\Decorator\TransactionalMessagingApiDecorator $decorator */
        $decorator = $this->getDecorator();
        if (method_exists($decorator, "testSendSmsToSingleRecipient")) {
            return $decorator->testSendSmsToSingleRecipient();
        }

        // Setting the model to use
        $this->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\CreateSmsDefinitionRequest"
        );

        // SUT
        $this->createResourceOnEndpoint();
        $this->executeOperation("PATCH", "sendSmsToSingleRecipient");
    }
}
