<?php
/**
 * GetQueueMetricsForSendDefinitionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SalesForce\MarketingCloud;

/**
 * GetQueueMetricsForSendDefinitionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetQueueMetricsForSendDefinitionResponse
 * @package     SalesForce\MarketingCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetQueueMetricsForSendDefinitionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetQueueMetricsForSendDefinitionResponse"
     */
    public function testGetQueueMetricsForSendDefinitionResponse()
    {
    }

    /**
     * Test attribute "requestId"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "ageSeconds"
     */
    public function testPropertyAgeSeconds()
    {
    }
}
